services:
  mysql:
    container_name: "hysteria-mysql"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  postgres:
    image: postgres:16.8
    container_name: "hysteria-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  mariadb:
    image: mariadb:10.5
    container_name: "hysteria-mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"

  redis:
    image: redis:6
    container_name: "hysteria-redis"
    environment:
      - REDIS_PASSWORD=root
    ports:
      - "6379:6379"

  mongo:
    image: mongo:4.4
    container_name: "hysteria-mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

  cockroach-init:
    image: "cockroachdb/cockroach:v25.1.1"
    depends_on:
      cockroachdb:
        condition: service_healthy
    volumes:
      - ./scripts/init_cockroachdb.sh:/init_cockroachdb.sh
    entrypoint: "/bin/bash"
    command: /init_cockroachdb.sh

  cockroachdb:
    image: "cockroachdb/cockroach:v25.1.1"
    container_name: "hysteria-cockroachdb"
    command: start-single-node --insecure
    environment:
      COCKROACH_USER: root
      COCKROACH_PASSWORD: root
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  cockroach-data:
    driver: local
