import { column } from "../decorators/model_decorators";
import { Model } from "../model";

/**
 * @description Mixin to add an autogenerated id column to a model
 */
export class AutogeneratedModel extends Model {
  @column.integer({
    primaryKey: true,
    type: "integer",
    openApi: {
      type: "number",
      required: true,
    },
  })
  declare id: number;
}
