export type HysteriaErrorCode =
  | "ROW_NOT_FOUND"
  | `UNSUPPORTED_DATABASE_TYPE_${string}`
  | "MODEL_HAS_NO_PRIMARY_KEY"
  | "INSERT_FAILED"
  | "CONNECTION_NOT_ESTABLISHED"
  | "TRANSACTION_NOT_ACTIVE";
