const whereTemplate = (tableName) => {
    return {
        where: (column, value, operator = "=") => `\nWHERE ${tableName}.${column} = ${value} `,
        andWhere: (column, value, operator = "=") => ` AND ${tableName}.${column} = ${value} `,
        orWhere: (column, value, operator = "=") => ` OR ${tableName}.${column} = ${value} `,
        whereNot: (column, value) => `\nWHERE ${tableName}.${column} != ${value} `,
        andWhereNot: (column, value) => ` AND ${tableName}.${column} != ${value} `,
        orWhereNot: (column, value) => ` OR ${tableName}.${column} != ${value} `,
        whereNull: (column) => `\nWHERE ${tableName}.${column} IS NULL `,
        andWhereNull: (column) => ` AND ${tableName}.${column} IS NULL `,
        orWhereNull: (column) => ` OR ${tableName}.${column} IS NULL `,
        whereNotNull: (column) => `\nWHERE ${tableName}.${column} IS NOT NULL `,
        andWhereNotNull: (column) => ` AND ${tableName}.${column} IS NOT NULL `,
        orWhereNotNull: (column) => ` OR ${tableName}.${column} IS NOT NULL `,
        whereBetween: (column, min, max) => `\nWHERE ${tableName}.${column} BETWEEN ${min} AND ${max} `,
        andWhereBetween: (column, min, max) => ` AND ${tableName}.${column} BETWEEN ${min} AND ${max} `,
        orWhereBetween: (column, min, max) => ` OR ${tableName}.${column} BETWEEN ${min} AND ${max} `,
        whereNotBetween: (column, min, max) => `\nWHERE ${tableName}.${column} NOT BETWEEN ${min} AND ${max} `,
        andWhereNotBetween: (column, min, max) => ` AND ${tableName}.${column} NOT BETWEEN ${min} AND ${max} `,
        orWhereNotBetween: (column, min, max) => ` OR ${tableName}.${column} NOT BETWEEN ${min} AND ${max} `,
        whereIn: (column, values) => `\nWHERE ${tableName}.${column} IN (${values.join(", ")}) `,
        andWhereIn: (column, values) => ` AND ${tableName}.${column} IN (${values.join(", ")}) `,
        orWhereIn: (column, values) => ` OR ${tableName}.${column} IN (${values.join(", ")}) `,
        whereNotIn: (column, values) => `\nWHERE ${tableName}.${column} NOT IN (${values.join(", ")}) `,
        andWhereNotIn: (column, values) => ` AND ${tableName}.${column} NOT IN (${values.join(", ")}) `,
        orWhereNotIn: (column, values) => ` OR ${tableName}.${column} NOT IN (${values.join(", ")}) `,
        rawWhere: (query) => `\nWHERE ${query} `,
        rawAndWhere: (query) => ` AND ${query} `,
        rawOrWhere: (query) => ` OR ${query} `,
    };
};
export default whereTemplate;
