import { AstParser } from "../../../src/sql/ast/parser";
import { AddColumnNode } from "../../../src/sql/ast/query/node/alter_table/add_column";
import { ColumnTypeNode } from "../../../src/sql/ast/query/node/column";
import { ConstraintNode } from "../../../src/sql/ast/query/node/constraint";
import { sqlFunc } from "../../../src/sql/ast/query/node/sqlfunc/sqlfunc";
import { Model } from "../../../src/sql/models/model";
import type { SqlDataSourceType } from "../../../src/sql/sql_data_source_types";

const stubModel = {
  table: "users",
  databaseCaseConvention: "preserve",
  modelCaseConvention: "preserve",
} as typeof Model;

const renderUuidColumn = (dbType: SqlDataSourceType, isForeignKey = false) => {
  const col = new ColumnTypeNode("id", "uuid");
  col.isForeignKey = isForeignKey;
  return new AstParser(stubModel, dbType).parse([col], 1, true).sql;
};

const renderAddColumn = (
  dbType: SqlDataSourceType,
  column: ColumnTypeNode,
  constraints?: ConstraintNode[],
) => {
  const node = new AddColumnNode(column);
  if (constraints) {
    node.inlineConstraints = constraints;
  }
  return new AstParser(stubModel, dbType).parse([node], 1, true).sql;
};

describe("uuid column DDL defaults", () => {
  test("mysql and mariadb get a native uuid default", () => {
    expect(renderUuidColumn("mysql")).toBe("`id` varchar(36) default (uuid())");
    expect(renderUuidColumn("mariadb")).toBe(
      "`id` varchar(36) default (uuid())",
    );
  });

  test("foreign-key uuid columns get no implicit default", () => {
    // A random FK default would violate the constraint on inserts that omit it.
    expect(renderUuidColumn("mysql", true)).toBe("`id` varchar(36)");
    expect(renderUuidColumn("postgres", true)).not.toContain("default");
    expect(renderUuidColumn("sqlite", true)).not.toContain("default");
  });

  test("postgres, sqlite and mssql keep their own uuid defaults", () => {
    expect(renderUuidColumn("postgres")).toBe(
      '"id" uuid default gen_random_uuid()',
    );
    expect(renderUuidColumn("sqlite")).toBe(
      '"id" varchar(36) default (lower(hex(randomblob(16))))',
    );
    expect(renderUuidColumn("mssql")).toBe(
      "[id] uniqueidentifier default NEWID()",
    );
  });
});

describe("ALTER ADD COLUMN on mysql must not carry a volatile uuid default", () => {
  // MySQL rejects `ADD COLUMN ... DEFAULT (uuid())` with ERROR 1674 (unsafe under
  // binlog, even with binlog_format=ROW and log_bin_trust_function_creators=ON),
  // and rejects a single multi-clause ALTER carrying the add plus a MODIFY. So
  // the ALTER path strips the default that CREATE TABLE legitimately emits, and
  // uuid values stay JS-generated by `prepare` for ORM inserts.
  test("the implicit uuid default is stripped from ADD COLUMN on mysql", () => {
    const sql = renderAddColumn("mysql", new ColumnTypeNode("ext", "uuid"));
    expect(sql).toBe("add column  `ext` varchar(36)");
    expect(sql).not.toContain("uuid()");
  });

  test("mariadb keeps the default, which it supports on ALTER", () => {
    const sql = renderAddColumn("mariadb", new ColumnTypeNode("ext", "uuid"));
    expect(sql).toContain("default (uuid())");
  });

  test("an explicit .default(sqlFunc.uuid()) is stripped too", () => {
    const sql = renderAddColumn("mysql", new ColumnTypeNode("ext", "uuid"), [
      new ConstraintNode("default", { defaultValue: sqlFunc.uuid() }),
    ]);
    expect(sql).not.toContain("uuid()");
  });

  test("a non-uuid ADD COLUMN keeps its own default", () => {
    const sql = renderAddColumn("mysql", new ColumnTypeNode("age", "int"), [
      new ConstraintNode("default", { defaultValue: "18" }),
    ]);
    expect(sql).toContain("default '18'");
  });

  test("CREATE TABLE still emits the default on mysql", () => {
    expect(renderUuidColumn("mysql")).toContain("default (uuid())");
  });
});
