import { PickMethods } from "../../utils/types";
import { Model } from "../models/model";
import { QueryBuilder } from "./query_builder";

export type QueryBuilderWithOnlyWhereConditions<T extends Model> = PickMethods<
  QueryBuilder<T>,
  | "where"
  | "andWhere"
  | "orWhere"
  | "whereSubQuery"
  | "andWhereSubQuery"
  | "orWhereSubQuery"
  | "whereBuilder"
  | "andWhereBuilder"
  | "orWhereBuilder"
  | "whereIn"
  | "andWhereIn"
  | "orWhereIn"
  | "whereNotIn"
  | "andWhereNotIn"
  | "orWhereNotIn"
  | "whereNull"
  | "andWhereNull"
  | "orWhereNull"
  | "whereNotNull"
  | "andWhereNotNull"
  | "orWhereNotNull"
  | "whereRegexp"
  | "andWhereRegexp"
  | "orWhereRegexp"
  | "whereBetween"
  | "andWhereBetween"
  | "orWhereBetween"
  | "whereNotBetween"
  | "andWhereNotBetween"
  | "orWhereNotBetween"
  | "whereIn"
  | "andWhereIn"
  | "orWhereIn"
  | "whereNotIn"
  | "andWhereNotIn"
  | "orWhereNotIn"
  | "whereNull"
  | "andWhereNull"
  | "orWhereNull"
  | "whereNotNull"
  | "andWhereNotNull"
  | "orWhereNotNull"
  | "whereRegexp"
  | "andWhereRegexp"
  | "orWhereRegexp"
  | "whereBetween"
  | "andWhereBetween"
  | "orWhereBetween"
  | "whereNotBetween"
  | "andWhereNotBetween"
  | "orWhereNotBetween"
>;
