import { AstParser } from "../../../ast/parser";
import { AddColumnNode } from "../../../ast/query/node/alter_table/add_column";
import { QueryNode } from "../../../ast/query/query";
import { Model } from "../../../models/model";
import { SqlDataSourceType } from "../../../sql_data_source_types";
import type { Interpreter } from "../../interpreter";

class MysqlAddColumnInterpreter implements Interpreter {
  declare model: typeof Model;
  declare dbType?: SqlDataSourceType;

  toSql(node: QueryNode) {
    const acNode = node as AddColumnNode;
    const ast = new AstParser(this.model, "mysql" as SqlDataSourceType);
    let { sql } = ast.parse([acNode.column]);

    const inlineConstraints = (acNode as any).inlineConstraints;
    if (inlineConstraints && inlineConstraints.length > 0) {
      const constraintParts: string[] = [];

      for (const constraint of inlineConstraints) {
        const { sql: constraintSql } = ast.parse([constraint]);
        constraintParts.push(constraintSql);
      }

      if (constraintParts.length > 0) {
        sql += ` ${constraintParts.join(" ")}`;
      }
    }

    // MySQL rejects a volatile-expression default on ALTER ADD (ERROR 1674: the
    // statement is unsafe under binlog, even with binlog_format=ROW and
    // log_bin_trust_function_creators=ON). It also rejects a single multi-clause
    // ALTER carrying the add plus a follow-up MODIFY, so there is no
    // one-statement form. MariaDB accepts it, so the strip is MySQL-only.
    //
    // On MySQL the column interpreter still emits the default for CREATE TABLE;
    // uuid values stay JS-generated by `prepare` for ORM inserts, so only rows
    // inserted outside the ORM are affected (they get NULL).
    if (this.dbType !== "mariadb") {
      sql = sql.replace(/\s+default\s+\(uuid\(\)\)/gi, "");
    }

    return { sql: `add column ${sql}`, bindings: [] };
  }
}

export default new MysqlAddColumnInterpreter();
