import { MongoDataSource } from "./mongo_data_source";
import { getBaseCollectionName } from "./mongo_model_types";

const collectionMap = new WeakMap<typeof MongoModel, string>();

export class MongoModel {
  /**
   * @description The sql sqlInstance generated by SqlDataSource.connect
   */
  static mongoInstance: MongoDataSource;

  /**
   * @description Collection name for the model, if not set it will be the plural snake case of the model name given that is in PascalCase (es. User -> users)
   */
  static collectionName: string;

  /**
   * @description Static getter for collection;
   * @internal
   */
  static get collection(): string {
    if (!collectionMap.has(this)) {
      collectionMap.set(
        this,
        this.collectionName || getBaseCollectionName(this),
      );
    }

    return collectionMap.get(this)!;
  }

  private static establishConnection(): void {
    const sql = MongoDataSource.getInstance();
    if (!sql) {
      throw new Error(
        "sql instance not initialized, did you defined it in SqlDataSource.connect static method?",
      );
    }

    this.mongoInstance = sql;
  }
}
