#!/usr/bin/env sh
set -eu

COMPOSE_FILE="docker-compose.worktrees.yml"
COMPOSE="docker compose -f $COMPOSE_FILE"

cleanup() {
  $COMPOSE down -v
}

trap cleanup EXIT HUP INT TERM

$COMPOSE up -d --wait \
  mysql postgres mariadb redis mongo cockroachdb mssql
$COMPOSE up -d cockroach-init
$COMPOSE wait cockroach-init
$COMPOSE run --rm --no-deps -T --build \
  -e HYSTERIA_WORKTREE_COMPOSE=1 \
  -e DB_HOST=postgres \
  -e DB_HOST_MYSQL=mysql \
  -e DB_HOST_MARIADB=mariadb \
  -e DB_PORT_MARIADB=3306 \
  -e DB_HOST_POSTGRES=postgres \
  -e DB_HOST_COCKROACHDB=cockroachdb \
  -e DB_HOST_MSSQL=mssql \
  -e MONGO_URL=mongodb://root:root@mongo:27017 \
  -e REDIS_HOST=redis \
  node sh -c "yarn install --frozen-lockfile && (ls node_modules/sqlite3/build/Release/*.node >/dev/null 2>&1 || (cd node_modules/sqlite3 && npx node-gyp rebuild)) && yarn test:with:migrations"
git add .
